version: '3.7'

services:
  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8765
    ports:
      - 8765:8765
    volumes:
      - ./backend:/usr/src/app/backend/
    depends_on:
      - db
      
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend:/usr/src/app/frontend/
    depends_on:
      - backend

  db:
    image: postgres:12-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    container_name: pgdb

volumes:
  postgres_data: