# Generated by Django 4.2.7 on 2023-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='daily_cost',
            field=models.FloatField(),
        ),
    ]
