# Generated by Django 4.2.7 on 2023-11-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_roombooks_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out_date',
        ),
    ]
